# Bubble Sort

In [62]:
for i in range(10,0,-1):
    print(i)

10
9
8
7
6
5
4
3
2
1


In [41]:
### Bubble sort 

In [64]:
def bubbleSort(a):
    
    for x in range(len(a)-1,0,-1):
        for i in range(x):
            if a[i] > a[i+1]:
                a[i],a[i+1] = a[i+1],a[i] 
    return a

In [67]:
a = [45,23,59,66,38,12,90,19,11,47,94,34,56,1]
bubbleSort(a)

[1, 11, 12, 19, 23, 34, 38, 45, 47, 56, 59, 66, 90, 94]

In [133]:
import numpy as np
a = np.random.randint(1,25,10)
a

array([15,  9,  6,  7,  4, 16,  3, 18, 21, 16])

In [134]:
bubbleSort(a)

array([ 3,  4,  6,  7,  9, 15, 16, 16, 18, 21])

# Improvment of bubble sort

In [165]:
def bubbleSortx(a):
    cc = 0
    for x in range(len(a)-1,0,-1):
        swap = 0
        cc = cc + 1
        for i in range(x):
            if a[i] > a[i+1]:
                a[i],a[i+1] = a[i+1],a[i]
                swap = swap + 1
        if swap == 0:
            break
    return a,cc

In [166]:
import numpy as np
a = np.random.randint(1,25,5)
a

array([ 7,  6, 20,  6, 18])

In [167]:
bubbleSortx(a)

(array([ 6,  6,  7, 18, 20]), 3)

In [169]:
a = [1,2,4,3,5]
bubbleSortx(a)

([1, 2, 3, 4, 5], 2)

In [172]:
# Range  Function 
for i in range(9):
    print(i)

0
1
2
3
4
5
6
7
8


In [173]:
for i in range(1,10):
    print(i)

1
2
3
4
5
6
7
8
9


# selctionSort

In [8]:
def selctionSort(a):
    for i in range(len(a)-1):
        minIndex = i 
        for j in range(i+1,len(a)):
            if a[j] <  a[minIndex]:
                minIndex = j
        if i != minIndex:
            a[i],a[minIndex] = a[minIndex],a[i]
    return a

In [14]:
import numpy as np
a = np.random.randint(1,100,10)
a

array([81, 75, 57, 91, 14,  8, 61, 94, 18,  1])

In [15]:
selctionSort(a)

array([ 1,  8, 14, 18, 57, 61, 75, 81, 91, 94])

In [16]:
# Insertion Sort